### ISSUE TITLE
Datadog API rate limits

### ISSUE THREAD

**Issue by joekohlsdorf** [DataDog/watermarkpodautoscaler#39]
Since this controller extracts metrics using the Datadog API I would like to know how this can be brought in line with the low API rate-limits for these kind of calls (source: https://docs.datadoghq.com/api/#rate-limiting):
- The rate limit for metric retrieval is 100 per hour per organization
- The rate limit for the query_batch API [...] call is 300 per hour per organization.

Additionally there is no way to monitor the current rate-limit budget so it just starts failing silently.

There should at least be some kind of warning in the README or information on what to do about this.

**Comment by CharlyF** [comment]
Hello @joekohlsdorf  - Thanks for opening this issue!
The controller supports any External Metrics Provider, including the [Datadog Cluster Agent](https://docs.datadoghq.com/agent/cluster_agent/).
We [released an image](https://hub.docker.com/layers/datadog/cluster-agent/1.4.0-wpa/images/sha256-512bdd505cc8392c3df207f33d70ffe21941186380388b4536f30753db40a10e) that supports both WPAs and HPAs using the informer framework. It's `datadog/cluster-agent:1.4.0-wpa`, you only need to add the environment variable `DD_EXTERNAL_METRICS_PROVIDER_WPA_CONTROLLER=true` as listed [here](https://github.com/DataDog/datadog-agent/blob/master/pkg/config/config.go#L455).

Apologies for the delay in documenting this, I will make sure this is better surfaced as soon as possible.

To answer your question, the Datadog Cluster Agent queries our APIs every 30 seconds and `query_batches` the metrics listed in the WPAs and HPAs, so it makes at most 120 calls/hour.

We are working with the upstream library that we use to make the client for our APIs to better surface the rate limit details, and this should be in the next release of the DCA.

Best,
.C

**Comment by AmitZoh** [comment]
Hi, I'm following up here since it's the only place I found any reference to this, but I'm experiencing a similar issue using image: datadog/cluster-agent:latests
My metrics aren't getting updated. I found the following error in the cluster agent log, so clearly it makes much more than 120 calls/hour:
	.rollup(30): API error 429 Too Many Requests: {
		"errors": ["Rate limit of 600 requests in 3600 seconds reached. Please try again later."]
	}

**Comment by CharlyF** [comment]
Hello @AmitZoh,

This is an issue that pertains to the Datadog API rate limits rather than the controller. In this case, could you reach out to the [solutions team](mailto:support@datadoghq.com) so they can bump your limits ?
Limits are shared across the org, so if the api/app keys are used for other purposes, it will consume the remaining quota. As for the Cluster Agent, it will make aggregate up to 35 metrics per call, made every 30s by default. So if you have 36 autoscalers, it will have 2 buckets which will yield 2 calls every 30 seconds and so on and so forth.

I will add a note in the readme as this controller is mostly used alongside the Cluster Agent, but this issue really pertains to the API rates associated with a Datadog account. Therefore, I am going to close this issue for now.

Best, 
.C

**Comment by minedetector** [comment]
Hello @CharlyF 

Just to make sure I understand correctly 1 custom metric will make 120 API calls and 30 custom metrics will also make the same 120 API calls but 36 custom metrics will start making 240 API calls, did I understand correctly what you meant by Cluster Agent aggregation ?

Main question is that is there a way to track the number of custom metrics in use ?
