### ISSUE TITLE
why not support cpu metrics？

### ISSUE THREAD

**Issue by iyacontrol** [DataDog/watermarkpodautoscaler#40]
thanks datadog. this is a exciting project. but why not support cpu metrics?

**Comment by CharlyF** [comment]
👋 @iyacontrol - Thanks a lot for opening this. 
We wanted to open source the code early on, but we could add the APIs to support other Metric Types.
We are also currently working on a Kubernetes Enhancement Proposal in order to push this upstream but I am adding this request to our backlog.

Best,
.C

**Comment by arapulido** [comment]
@CharlyF I guess this one can be closed now?

**Comment by CharlyF** [comment]
No, we merged the change but there is more work needed and we have not released yet - I will close then 👍

**Comment by arapulido** [comment]
@CharlyF Thanks for the clarification!

**Comment by cforce** [comment]
No update since over a year - is this project dead?

**Comment by CharlyF** [comment]
[Resource metrics](https://github.com/DataDog/watermarkpodautoscaler/blob/main/config/crd/bases/v1beta1/datadoghq.com_watermarkpodautoscalers.yaml#L154-L160) have been introduced in the previous minor version, you can use the WPA controller alongside the metrics server to scale off of CPU/mem.

Let us know if you face any issues!
